import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "uk" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uk: {
    // Header
    catalog: "Каталог товарів",
    allProducts: "Всі товари",
    fpvDrones: "FPV Дрони",
    batteries: "Акумулятори",
    fiberOptic: "Оптоволокно",
    printing3d: "3D Друк",
    
    // Hero Carousel
    heroFpvTitle: "FPV ДРОНИ",
    heroFpvSubtitle: "НА ЗАМОВЛЕННЯ",
    heroFpvBadge: "Виготовлення будь-якого розміру",
    heroBatteryTitle: "АКУМУЛЯТОРИ",
    heroBatterySubtitle: "НА ЗАМОВЛЕННЯ",
    heroBatteryBadge: "Індивідуальна збірка",
    heroFiberTitle: "КОТУШКИ З ОПТОВОЛОКНОМ",
    heroFiberSubtitle: "НА ЗАМОВЛЕННЯ",
    heroFiberBadge: "Професійне обладнання",
    hero3dTitle: "3D ДРУК",
    hero3dSubtitle: "НА ЗАМОВЛЕННЯ",
    hero3dBadge: "Деталі для дронів",
    
    // About Section
    aboutTitle: "Flugart — інноваційні рішення для безпілотних технологій",
    aboutText: "Ми — компанія Flugart, яка спеціалізується на виготовленні FPV дронів різних розмірів, створенні акумуляторів на замовлення, виробництві оптоволоконних котушок та 3D друку деталей для дронів. Наша команда забезпечує високу якість та індивідуальний підхід до кожного замовлення.",
    
    // Features Ticker
    feature1: "Комплектуючі перевірених світових брендів",
    feature2: "Більш ніж 20 000 збірок щомісяця",
    feature3: "Експертний досвід у виробництві",
    feature4: "Тестування та перевірка кожного виробу",
    feature5: "Власний R&D відділ в Україні",
    feature6: "Високоякісне українське виробництво",
    
    // Categories
    ourServices: "Наші послуги",
    view: "Переглянути",
    variousSizes: "різних розмірів",
    customOrder: "на замовлення",
    forDrones: "для дронів",
    onDemand: "на замовлення",
    
    // Footer
    footerDescription: "Інноваційні технології для FPV дронів та комплектуючих преміальної якості.",
    footerCatalog: "Каталог",
    footerInfo: "Інформація",
    footerContacts: "Контакти",
    footerAbout: "Про компанію",
    footerAboutText: "Flugart — українська компанія, що спеціалізується на виробництві FPV дронів, акумуляторів, оптоволоконних котушок та 3D друку комплектуючих. Працюємо з 2022 року, виконуємо індивідуальні замовлення.",
    footerDelivery: "Доставка та оплата",
    footerWarranty: "Гарантія",
    footerWarrantyTitle: "Гарантія",
    footerWarrantyText: "6 місяців на всю продукцію власного виробництва. Гарантія не поширюється на механічні пошкодження та неправильну експлуатацію.",
    footerContact: "Контакти",
    footerRights: "© 2024 Flugart. Всі права захищені.",
    footerPrivacy: "Політика конфіденційності",
    footerTerms: "Умови використання",
    footerBatteriesCustom: "Акумулятори на замовлення",
    
    // About Page
    aboutPageTitle: "Про компанію Flugart",
    aboutPageSubtitle: "Інноваційні рішення для безпілотних технологій",
    aboutMissionTitle: "Наша місія",
    aboutMissionText: "Flugart створює надійні та високоякісні рішення для безпілотних систем. Ми віримо, що українські технології мають бути найкращими у світі, і щодня працюємо над цим.",
    aboutHistoryTitle: "Історія компанії",
    aboutHistoryText: "Компанія Flugart заснована у 2022 році в Україні. За цей час ми виконали тисячі замовлень та побудували репутацію надійного партнера для пілотів FPV та організацій, що використовують безпілотні технології.",
    aboutServicesTitle: "Що ми робимо",
    aboutService1: "Виробництво FPV дронів різних розмірів (8\", 10\", 13\", 15\") серій TAIPAN та MAMBA",
    aboutService2: "Збірка акумуляторів під індивідуальні потреби замовника",
    aboutService3: "Виготовлення котушок з оптоволокном для далекобійних систем",
    aboutService4: "3D друк комплектуючих та деталей для дронів",
    aboutTeamTitle: "Наша команда",
    aboutTeamText: "Команда Flugart — це досвідчені інженери, конструктори та пілоти FPV, які розуміють потреби клієнтів. Власний R&D відділ постійно працює над удосконаленням продукції.",
    aboutValuesTitle: "Наші цінності",
    aboutValue1: "Якість — використовуємо лише перевірені комплектуючі світових брендів",
    aboutValue2: "Індивідуальний підхід — кожне замовлення виконується з урахуванням потреб клієнта",
    aboutValue3: "Відповідальність — тестуємо кожен виріб перед відправкою",
    aboutLocationTitle: "Розташування",
    aboutLocationText: "Ми базуємося в Україні та здійснюємо доставку по всій території країни.",
    
    // Delivery Page
    deliveryPageTitle: "Доставка та оплата",
    deliveryPageSubtitle: "Індивідуальний підхід до кожного замовлення",
    deliveryInfoTitle: "Умови доставки та виготовлення",
    deliveryInfoText: "Терміни доставки та виготовлення розраховуються індивідуально для кожного замовлення. Вартість доставки також залежить від специфіки замовлення.",
    deliveryGeographyTitle: "Географія доставки",
    deliveryGeographyText: "Здійснюємо доставку по всій території України. Для замовлень з інших країн зв'яжіться з нами для обговорення умов.",
    paymentMethodsTitle: "Способи оплати",
    paymentCard: "Оплата карткою",
    paymentCardText: "Безпечна оплата банківською карткою Visa/Mastercard.",
    paymentPrepayment: "Передоплата",
    paymentPrepaymentText: "Для товарів на замовлення може знадобитися часткова або повна передоплата. Умови обговорюються індивідуально.",
    deliveryQuestionsTitle: "Є питання?",
    deliveryQuestionsText: "Зв'яжіться з нами за телефоном для уточнення деталей доставки та оплати:",
    deliveryQuestionsTextEmail: "Зв'яжіться з нами для уточнення деталей доставки та оплати:",
    
    // Warranty Page
    warrantyPageTitle: "Гарантія",
    warrantyPageSubtitle: "Умови гарантійного обслуговування продукції Flugart",
    warrantyPeriod: "6 місяців",
    warrantyPeriodText: "на всю продукцію власного виробництва",
    warrantyTermsTitle: "Загальні умови",
    warrantyTerm1: "Гарантійний термін 6 місяців з дати отримання товару",
    warrantyTerm2: "Гарантія поширюється на продукцію власного виробництва Flugart",
    warrantyTerm3: "Для гарантійного звернення збережіть документ про покупку",
    warrantyCoveredTitle: "Що покриває гарантія",
    warrantyCovered1: "Виробничі дефекти та брак матеріалів",
    warrantyCovered2: "Несправності електронних компонентів при правильній експлуатації",
    warrantyCovered3: "Проблеми з акумуляторами (окрім природного зношення)",
    warrantyCovered4: "Дефекти збірки та пайки",
    warrantyNotCoveredTitle: "Що не покриває гарантія",
    warrantyNotCovered1: "Механічні пошкодження внаслідок падінь, ударів, аварій",
    warrantyNotCovered2: "Пошкодження від неправильної експлуатації (перевищення навантаження, неправильна зарядка)",
    warrantyNotCovered3: "Природне зношення компонентів",
    warrantyNotCovered4: "Самостійний ремонт або модифікація виробу",
    warrantyClaimTitle: "Як звернутися за гарантією",
    warrantyClaim1: "Зв'яжіться з нами за телефоном або через форму зворотного зв'язку",
    warrantyClaim2: "Опишіть проблему та надайте фото/відео дефекту",
    warrantyClaim3: "Після підтвердження гарантійного випадку відправте товар на наш склад",
    warrantyClaim4: "Ми виконаємо ремонт або заміну протягом 14 робочих днів",
    warrantyContactTitle: "Контакт для гарантійних звернень",
    warrantyContactText: "Для гарантійних звернень зв'яжіться з нами:",
    warrantyContactTextEmail: "Для гарантійних звернень напишіть нам:",
    
    // Search Results
    home: "Головна",
    search: "Пошук",
    searchPlaceholder: "Пошук...",
    searchProductsPlaceholder: "Пошук товарів...",
    showAllResults: "Показати всі результати",
    nothingFoundFor: "Нічого не знайдено за запитом",
    searchResults: "Результати пошуку",
    allCategories: "Всі категорії",
    categories: "Категорії",
    foundProducts: "Знайдено товарів",
    product: "товар",
    products234: "товари",
    products5plus: "товарів",
    nothingFound: "Нічого не знайдено",
    tryChangingSearch: "Спробуйте змінити пошуковий запит або перегляньте наші категорії",
    toHome: "На головну",
    
    // Product Page
    inStock: "В наявності",
    outOfStock: "Немає в наявності",
    pcs: "шт.",
    quantity: "Кількість",
    buyNow: "Купити зараз",
    addToCart: "У кошик",
    addToFavorites: "В обране",
    inFavorites: "В обраному",
    addedToFavorites: "Додано до обраного",
    removedFromFavorites: "Видалено з обраного",
    share: "Поділитися",
    delivery: "Доставка",
    allUkraine: "По всій Україні",
    warranty: "Гарантія",
    months6: "6 місяців",
    returns: "Повернення",
    days14: "14 днів",
    specifications: "Характеристики",
    features: "Переваги",
    addedToCart: "Додано до кошика",
    
    // Cart
    cart: "Кошик",
    favorites: "Обране",
    clear: "Очистити",
    cartEmpty: "Кошик порожній",
    favoritesEmpty: "Обране порожнє",
    addProductsToOrder: "Додайте товари для оформлення замовлення",
    addProductsToFavorites: "Додайте товари до обраного",
    continueShopping: "Продовжити покупки",
    yourSavings: "Ваша економія",
    total: "Разом",
    checkout: "Оформити замовлення",
    
    // Checkout
    orderCheckout: "Оформлення замовлення",
    goBack: "Повернутись назад",
    contactInfo: "Контактні дані",
    firstName: "Ім'я",
    lastName: "Прізвище",
    phone: "Телефон",
    email: "Email",
    enterFirstName: "Введіть ім'я",
    enterLastName: "Введіть прізвище",
    enterPhone: "Введіть номер телефону",
    deliveryMethod: "Спосіб доставки",
    novaPoshta: "Нова Пошта",
    toWarehouse: "Доставка у відділення",
    courier: "Кур'єр",
    toAddress: "Доставка за адресою",
    city: "Місто",
    enterCity: "Введіть місто",
    warehouseNumber: "Номер відділення",
    deliveryAddress: "Адреса доставки",
    paymentMethod: "Спосіб оплати",
    cardPayment: "Оплата карткою",
    cashOnDelivery: "Накладений платіж",
    payOnReceive: "Оплата при отриманні",
    deliveryDiscussedPersonally: "Спосіб доставки обговорюється особисто",
    paymentOnReceipt: "Оплата при отриманні",
    orderComment: "Коментар до замовлення",
    additionalInfo: "Додаткова інформація про замовлення...",
    yourOrder: "Ваше замовлення",
    discount: "Знижка",
    deliveryCost: "За тарифами перевізника",
    confirmOrder: "Підтвердити замовлення",
    agreeToTerms: "Натискаючи кнопку, ви погоджуєтесь з умовами публічної оферти",
    orderPlaced: "Замовлення оформлено!",
    willContactYou: "Ми зв'яжемось з вами найближчим часом",
    error: "Помилка",
    fillAllFields: "Будь ласка, заповніть всі обов'язкові поля",
    
    // Validation errors
    enterName: "Введіть ім'я",
    enterSurname: "Введіть прізвище",
    enterPhoneNumber: "Введіть номер телефону",
    enterEmail: "Введіть email",
    invalidEmail: "Невірний формат email",
    enterWarehouse: "Введіть номер відділення",
    enterAddress: "Введіть адресу доставки",
    
    // 404
    pageNotFound: "Сторінку не знайдено",
    returnToHome: "Повернутись на головну",
    
    // Category names
    "catFpvDrones": "FPV Дрони",
    "catBatteries": "Акумулятори",
    "catFiberOptic": "Оптоволокно",
    "cat3dPrinting": "3D Друк",
    "accessories": "Аксесуари",
    
    // Popular products
    popularProducts: "Популярні пропозиції",
    
    // Product names
    "product_fpv_5_freestyle": "FPV Дрон 5\" Freestyle",
    "product_fpv_7_longrange": "FPV Дрон 7\" Long Range",
    "product_fpv_3_cinewhoop": "FPV Дрон 3\" Cinewhoop",
    "product_fpv_10_heavylift": "FPV Дрон 10\" Heavy Lift",
    "product_battery_lipo_6s": "Акумулятор LiPo 6S 1300mAh",
    "product_battery_lipo_4s": "Акумулятор LiPo 4S 1500mAh",
    "product_battery_liion_21700": "Акумулятор Li-Ion 21700 збірка",
    "product_fiber_old_15km": "Оптоволоконна котушка 15км",
    "product_fiber_old_20km": "Оптоволоконна котушка 20км",
    "product_fiber_old_25km": "Оптоволоконна котушка 25км",
    "product_3d_drone_case": "3D друк корпусу для дрона",
    "product_3d_camera_mount": "3D друк кріплення камери",
    "product_3d_protection_frame": "3D друк захисної рами",
    "product_3d_antenna_holder": "3D друк антенного тримача",
    
    // Product page details
    "product1_title": "BTRY 6s2p Lishen (LR2170LA)",
    "product1_description": "Високоякісна акумуляторна збірка BTRY 6s2p на базі елементів Lishen LR2170LA. Ідеально підходить для FPV дронів середнього та великого розміру.",
    "product1_feature1": "Висока ємність для тривалого польоту",
    "product1_feature2": "Стабільна віддача струму до 90A",
    "product1_feature3": "Захист від перезаряду та перерозряду",
    "product1_feature4": "Термостійке покриття корпусу",
    "product1_feature5": "Якісне точкове зварювання",
    "product1_feature6": "Гарантія 6 місяців",
    
    "product2_title": "Molicel INR21700-P42A",
    "product2_description": "Оригінальний високотоковий елемент Molicel INR21700-P42A. Один з найкращих елементів для FPV збірок завдяки високому струму віддачі та стабільності.",
    "product2_feature1": "Оригінальні елементи Molicel",
    "product2_feature2": "Висока струмовіддача 45A",
    "product2_feature3": "Низький внутрішній опір",
    "product2_feature4": "Стабільна робота при низьких температурах",
    
    "product3_title": "BTRY Термоконтейнер з підігрівом",
    "product3_description": "Професійний термоконтейнер з вбудованим підігрівом для зберігання та транспортування Li-ion акумуляторів в холодну пору року.",
    "product3_feature1": "Вбудована система підігріву",
    "product3_feature2": "Камуфляжне забарвлення",
    "product3_feature3": "Ударостійкий корпус",
    "product3_feature4": "Герметичне закриття",
    
    // Specification labels
    "spec_configuration": "Конфігурація",
    "spec_capacity": "Ємність",
    "spec_voltage": "Напруга",
    "spec_voltage_nominal": "22.2V (номінальна)",
    "spec_voltage_nominal_36": "3.6V (номінальна)",
    "spec_max_current": "Максимальний струм",
    "spec_weight": "Вага",
    "spec_dimensions": "Розміри",
    "spec_cells": "Елементи",
    "spec_bms": "BMS",
    "spec_bms_builtin": "Вбудована захисна плата",
    "spec_form_factor": "Типорозмір",
    "spec_material": "Матеріал",
    "spec_impact_resistant_plastic": "Ударостійкий пластик",
    "spec_insulation": "Утеплення",
    "spec_thermal_insulation": "Термоізоляція 20мм",
    "spec_heating": "Підігрів",
    "spec_up_to_12_batteries": "До 12 акумуляторів",
    
    // Fiber optic
    "fiber_15km_description": "Оптоволоконна котушка довжиною 15 км для FPV дронів. Забезпечує стабільний зв'язок на великих відстанях з мінімальними втратами сигналу.",
    "fiber_20km_description": "Оптоволоконна котушка довжиною 20 км для FPV дронів. Ідеальний вибір для середньої дальності польоту з високою якістю передачі даних.",
    "fiber_25km_description": "Оптоволоконна котушка довжиною 25 км для FPV дронів. Максимальна дальність для професійних операцій з безперебійним зв'язком.",
    "spec_length": "Довжина",
    "spec_fiber_type": "Тип волокна",
    "spec_single_mode": "Одномодове",
    "spec_core_diameter": "Діаметр сердечника",
    "spec_attenuation": "Загасання",
    "fiber_feature1": "Стабільний зв'язок на великих відстанях",
    "fiber_feature2": "Мінімальні втрати сигналу",
    "fiber_feature4": "Стійкість до електромагнітних завад",
    
    // Drone specs translations
    "spec_flight_stack": "Політний стек",
    "spec_motors": "Двигуни",
    "spec_frame": "Рама",
    "spec_video_tx": "Відеопередавач",
    "spec_camera": "Відеокамера",
    "spec_receiver": "Приймач",
    "spec_propellers": "Пропелери",
    "spec_battery": "Акумулятор",
    "spec_antenna": "Антена",
    "spec_fiber_optic": "Оптоволокно",
    
    // Drone features translations
    "feature_carbon_frame": "Карбонова рама",
    "feature_day_camera": "Денна камера",
    "feature_thermal_camera": "Тепловізійна камера",
    "feature_lowlight_camera": "Сутінкова камера",
    "feature_diversity_camera": "Diversity камера",
    "feature_powerful_vtx": "Потужний відеопередавач",
    "feature_fiber_optic": "Оптоволокно",
    "feature_rotary_mount": "Поворотне кріплення камери",
    "feature_3d_printed_case": "3D друкований корпус",
    "feature_quick_mount": "Швидке монтування",
    "feature_stable_connection": "Стабільний зв'язок без перешкод",
    
    // Additional UI
    linkCopied: "Посилання скопійовано",
    menu: "Меню",
    language: "Мова",
    callUs: "Зателефонувати",
    sortBy: "Сортувати",
    priceAsc: "Ціна: від низької",
    priceDesc: "Ціна: від високої",
    nameAz: "Назва: А-Я",
    nameZa: "Назва: Я-А",
    product_fiber_10km: "Котушка з оптоволокном 10 км",
    product_fiber_15km: "Котушка з оптоволокном 15 км",
    product_fiber_20km: "Котушка з оптоволокном 20 км",
    location: "Україна, м. Київ",
    defaultSort: "За замовчуванням",
    configurator: "Конфігуратор",
    
    // Hero MAMBA slide
    heroMambaTitle: "БпАК (БпЛА)",
    heroMambaSubtitle: "МАМБА",
    heroMambaBadge: "Максимальна дальність",
    
    // Ground stations
    groundStations: "Наземні станції",
    controlSystems: "системи керування",
    
    // Hero Taipan Kit slide
    heroTaipanKitTitle: "БпАК (БпЛА)",
    heroTaipanKitSubtitle: "ТАЙПАН",
    heroTaipanKitBadge: "Повний набір обладнання",
    
    // UAV category
    uavKits: "БпАК",
    completeKits: "Комплекти БпАК",
    fullEquipment: "повний набір",
    priceOnRequest: "Орієнтовна ціна: в залежності від замовлення",
    estimatedPrice: "Орієнтовна ціна",
    dependsOnOrder: "в залежності від замовлення",
    socialMedia: "Соціальні мережі",
    fiberSpools: "Котушки з оптоволокном",
    groundStationsCategory: "Наземні станції",
    techSupport: "Тех. підтримка",
    ordersDesk: "Стіл замовлень",
    
    // Live Chat
    liveChat: "Чат підтримки",
    chatWelcome: "Вітаємо! Як ми можемо вам допомогти?",
    chatStartMessage: "Напишіть своє повідомлення і ми відповімо найближчим часом",
    typeMessage: "Введіть повідомлення...",
    
    // Footer
    footerInstruction: "Інструкція",
    
    // Contact Page
    contactPage: "Контакти",
    contactDescription: "Зв'яжіться з нами для консультації або оформлення замовлення. Ми завжди раді допомогти!",
    sendMessage: "Надіслати повідомлення",
    yourName: "Ваше ім'я",
    yourMessage: "Ваше повідомлення",
    enterMessage: "Введіть повідомлення",
    sendButton: "Надіслати",
    sending: "Надсилається...",
    messageSent: "Повідомлення надіслано!",
    addressLabel: "Адреса",
    legalDocuments: "Юридичні документи",
    privacyPolicy: "Політика конфіденційності",
    termsOfUse: "Умови використання",
    
    // Privacy Policy
    privacyIntroTitle: "Загальні положення",
    privacyIntroText: "Ця Політика конфіденційності описує, як Flugart збирає, використовує та захищає персональні дані користувачів нашого веб-сайту та сервісів.",
    privacyDataCollectionTitle: "Які дані ми збираємо",
    privacyDataCollectionText: "Ми можемо збирати наступні типи персональних даних:",
    privacyDataItem1: "Контактні дані (ім'я, електронна пошта, телефон)",
    privacyDataItem2: "Інформація про замовлення та адреса доставки",
    privacyDataItem3: "Технічна інформація (IP-адреса, тип браузера)",
    privacyDataItem4: "Дані про взаємодію з сайтом",
    privacyDataUseTitle: "Як ми використовуємо ваші дані",
    privacyDataUseText: "Зібрані дані використовуються для:",
    privacyUseItem1: "Обробки та виконання замовлень",
    privacyUseItem2: "Зв'язку з вами щодо замовлень та підтримки",
    privacyUseItem3: "Покращення якості наших послуг",
    privacyDataProtectionTitle: "Захист даних",
    privacyDataProtectionText: "Ми вживаємо всіх необхідних технічних та організаційних заходів для захисту ваших персональних даних від несанкціонованого доступу, втрати або знищення.",
    privacyRightsTitle: "Ваші права",
    privacyRightsText: "Ви маєте право:",
    privacyRightsItem1: "Отримати доступ до своїх персональних даних",
    privacyRightsItem2: "Вимагати виправлення або видалення даних",
    privacyRightsItem3: "Відкликати згоду на обробку даних",
    privacyContactTitle: "Контакти",
    privacyContactText: "З питань щодо конфіденційності звертайтесь:",
    privacyLastUpdated: "Останнє оновлення",
    
    // Terms of Use
    termsGeneralTitle: "Загальні умови",
    termsGeneralText: "Використовуючи наш веб-сайт та послуги, ви погоджуєтесь з цими умовами. Flugart залишає за собою право змінювати умови без попереднього повідомлення.",
    termsOrdersTitle: "Замовлення та оплата",
    termsOrdersText: "При оформленні замовлення:",
    termsOrdersItem1: "Ціни на товари можуть змінюватися без попереднього повідомлення",
    termsOrdersItem2: "Замовлення вважається підтвердженим після зв'язку з менеджером",
    termsOrdersItem3: "Для кастомних виробів може знадобитися передоплата",
    termsPaymentTitle: "Оплата",
    termsPaymentText: "Ми приймаємо оплату карткою або готівкою при отриманні. Для індивідуальних замовлень умови оплати обговорюються окремо.",
    termsDeliveryTitle: "Доставка",
    termsDeliveryText: "Доставка здійснюється службами Нова Пошта по всій Україні. Терміни та вартість доставки залежать від обраного методу та регіону.",
    termsWarrantyTitle: "Гарантія",
    termsWarrantyText: "Гарантійний термін на наші вироби складає 6 місяців з моменту отримання. Гарантія не поширюється на механічні пошкодження та неправильну експлуатацію.",
    termsLiabilityTitle: "Обмеження відповідальності",
    termsLiabilityText: "Flugart не несе відповідальності за неправильне використання продукції. Дрони та обладнання повинні використовуватися відповідно до законодавства України.",
    termsChangesTitle: "Зміни умов",
    termsChangesText: "Ми залишаємо за собою право змінювати ці умови в будь-який час. Продовжуючи користуватися сайтом, ви погоджуєтесь з оновленими умовами.",
    termsLastUpdated: "Останнє оновлення",
    
    // Instructions page
    instructionTitle: "Інструкція з експлуатації БпЛА",
    instructionIntro: "Детальна інструкція з підготовки та експлуатації безпілотного літального апарату з оптоволоконним з'єднанням.",
    checkUavCompleteness: "Перевірте комплектність БпЛА",
    uavItem1: "Акумулятор",
    uavItem2: "Котушка оптоволоконного кабелю, фіксатор котушки",
    uavItem3: "Плата ініціації",
    uavItem4: "Ремінці на липучці або пластикові кріпильні хомути (стяжки)",
    checkStationCompleteness: "Перевірте комплектність наземної станції",
    stationItem1: "Перетворювач сигналу",
    stationItem2: "Акумулятор",
    stationItem3: "Відео-кабель",
    prepareForOperation: "Підготовка до експлуатації",
    prepareStep1: "Встановіть котушку на відповідне кріплення знизу БпЛА у напрямку від камери назад до упору, вставте фіксатор котушки у відповідний отвір на кріпленні",
    prepareStep2: "Під'єднайте обережно кабель від БпЛА до котушки",
    prepareStep3: "Встановіть БЧ",
    prepareStep4: "Встановіть плату ініціації безпосередньо на БЧ або у відповідне місце кріплення на рамі БпЛА збоку, зафіксуйте стяжками, під'єднайте детонатор БЧ до плати ініціації, за необхідності під'єднайте плату ініціації до БпЛА (зелений роз'єм)",
    prepareStep5: "Встановіть акумулятор у відповідне місце, задня частина БпЛА між рамою та котушкою, зафіксуйте ременями або стяжками",
    controllerSettings: "Налаштування пульту керування",
    controllerSettingsIntro: "У налаштуваннях пульта увімкніть зовнішній модуль (External) у PPM режимі. Для керування БпЛА використовуються наступні канали:",
    channelAETR: "стандартна послідовність AETR",
    channelARM: "запуск моторів (ARM): СТОП ~1000, СТАРТ ~2000",
    channelModes: "режими польоту: ACRO ~1000, ANGLE ~1500, HORIZON ~2000",
    channelActivation: "активація БЧ ~2000",
    preFlightPrep: "Підготовка до зльоту",
    preFlightIntro: "Перевірте балансування зібраного БпЛА, центр ваги має бути посередині або із незначним відхиленням уперед. Правильне балансування дозволить ефективніше використовувати запас енергії акумулятора у польоті.",
    preFlightPlace: "Встановіть БпЛА на спеціальну підставку або використайте підручні засоби.",
    spoolPrep: "Підготовка котушки:",
    spoolStep1: "Зріжте стяжку та вийміть запобіжники виходу оптоволоконного кабелю",
    spoolStep2: "Зніміть захисну червону стрічку і захисний ковпачок",
    spoolStep3: "ОБЕРЕЖНО зніміть захисний ковпачок на конекторі",
    spoolStep4: "ОБЕРЕЖНО витягніть достатню кількість кабелю та під'єднайте до наземної станції",
    spoolStep5: "ЗАБОРОНЯЄТЬСЯ згинати оптоволоконний кабель",
    connectionStep1: "Під'єднайте акумулятор наземної станції до перетворювача сигналу, під'єднайте відео-кабель відповідним кінцем до перетворювача сигналу, іншим до окулярів або монітору, під'єднайте кабель до пульту керування",
    connectionStep2: "Увімкніть наземну станцію, окуляри чи монітор, пульт керування",
    connectionStep3: "Під'єднайте кабель живлення БпЛА, перевірте світлову індикацію на котушці та наземній станції, перевірте відео в окулярах або на моніторі",
    connectionStep4: "Увімкніть мотори відповідним перемикачем на пульті, усі пропелери мають обертатись, напрямок обертання «на камеру»",
    takeoffTitle: "Зліт",
    takeoffText: "Злітайте вгору і вперед. У момент зльоту тримайте оптоволоконний кабель, дочекайтесь поки він ляже на землю, кущі, дерева тощо, після чого кабель можна більше не утримувати.",
    flightControlTitle: "Керування у польоті",
    flightControlWarning: "Уникайте різкого маневрування, зупинки і ОСОБЛИВО польоту заднім ходом, це може призвести до обриву оптоволоконного кабелю.",
    happyFlight: "Бажаємо приємного польоту та вдалого його завершення!",
  },
  en: {
    // Header
    catalog: "Product Catalog",
    allProducts: "All Products",
    fpvDrones: "FPV Drones",
    batteries: "Batteries",
    fiberOptic: "Fiber Optic",
    printing3d: "3D Printing",
    
    // Hero Carousel
    heroFpvTitle: "FPV DRONES",
    heroFpvSubtitle: "CUSTOM MADE",
    heroFpvBadge: "Manufacturing any size",
    heroBatteryTitle: "BATTERIES",
    heroBatterySubtitle: "TO ORDER",
    heroBatteryBadge: "Individual assembly",
    heroFiberTitle: "FIBER OPTIC SPOOLS",
    heroFiberSubtitle: "TO ORDER",
    heroFiberBadge: "Professional equipment",
    hero3dTitle: "3D PRINTING",
    hero3dSubtitle: "ON DEMAND",
    hero3dBadge: "Drone parts",
    heroMambaTitle: "UAV (UAS)",
    heroMambaSubtitle: "MAMBA",
    heroMambaBadge: "Maximum range",
    
    // Ground stations
    groundStations: "Ground Stations",
    controlSystems: "control systems",
    
    // Hero Taipan Kit slide
    heroTaipanKitTitle: "UAV (UAS)",
    heroTaipanKitSubtitle: "TAIPAN",
    heroTaipanKitBadge: "Complete equipment set",
    
    // UAV category
    uavKits: "UAV",
    completeKits: "UAV Kits",
    fullEquipment: "full set",
    priceOnRequest: "Estimated price: depends on order",
    estimatedPrice: "Estimated price",
    dependsOnOrder: "depends on order",
    socialMedia: "Social Media",
    fiberSpools: "Fiber Optic Spools",
    groundStationsCategory: "Ground Stations",
    techSupport: "Tech Support",
    ordersDesk: "Orders Desk",
    
    // Live Chat
    liveChat: "Live Chat",
    chatWelcome: "Welcome! How can we help you?",
    chatStartMessage: "Write your message and we'll respond as soon as possible",
    typeMessage: "Type a message...",
    
    // Contact Page
    contactPage: "Contact",
    contactDescription: "Get in touch with us for consultation or to place an order. We're always happy to help!",
    sendMessage: "Send a message",
    yourName: "Your name",
    yourMessage: "Your message",
    enterMessage: "Enter your message",
    sendButton: "Send",
    sending: "Sending...",
    messageSent: "Message sent!",
    addressLabel: "Address",
    legalDocuments: "Legal Documents",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    
    // Privacy Policy
    privacyIntroTitle: "General Provisions",
    privacyIntroText: "This Privacy Policy describes how Flugart collects, uses, and protects the personal data of users of our website and services.",
    privacyDataCollectionTitle: "Data We Collect",
    privacyDataCollectionText: "We may collect the following types of personal data:",
    privacyDataItem1: "Contact information (name, email, phone)",
    privacyDataItem2: "Order information and delivery address",
    privacyDataItem3: "Technical information (IP address, browser type)",
    privacyDataItem4: "Site interaction data",
    privacyDataUseTitle: "How We Use Your Data",
    privacyDataUseText: "Collected data is used for:",
    privacyUseItem1: "Processing and fulfilling orders",
    privacyUseItem2: "Contacting you about orders and support",
    privacyUseItem3: "Improving the quality of our services",
    privacyDataProtectionTitle: "Data Protection",
    privacyDataProtectionText: "We take all necessary technical and organizational measures to protect your personal data from unauthorized access, loss, or destruction.",
    privacyRightsTitle: "Your Rights",
    privacyRightsText: "You have the right to:",
    privacyRightsItem1: "Access your personal data",
    privacyRightsItem2: "Request correction or deletion of data",
    privacyRightsItem3: "Withdraw consent for data processing",
    privacyContactTitle: "Contact",
    privacyContactText: "For privacy inquiries, contact:",
    privacyLastUpdated: "Last updated",
    
    // Terms of Use
    termsGeneralTitle: "General Terms",
    termsGeneralText: "By using our website and services, you agree to these terms. Flugart reserves the right to change terms without prior notice.",
    termsOrdersTitle: "Orders and Payment",
    termsOrdersText: "When placing an order:",
    termsOrdersItem1: "Product prices may change without prior notice",
    termsOrdersItem2: "Order is considered confirmed after manager contact",
    termsOrdersItem3: "Custom products may require prepayment",
    termsPaymentTitle: "Payment",
    termsPaymentText: "We accept card payment or cash on delivery. For custom orders, payment terms are discussed separately.",
    termsDeliveryTitle: "Delivery",
    termsDeliveryText: "Delivery is carried out by Nova Poshta throughout Ukraine. Delivery times and costs depend on the chosen method and region.",
    termsWarrantyTitle: "Warranty",
    termsWarrantyText: "Warranty period for our products is 6 months from the date of receipt. Warranty does not cover mechanical damage and improper use.",
    termsLiabilityTitle: "Limitation of Liability",
    termsLiabilityText: "Flugart is not responsible for improper use of products. Drones and equipment must be used in accordance with Ukrainian legislation.",
    termsChangesTitle: "Changes to Terms",
    termsChangesText: "We reserve the right to change these terms at any time. By continuing to use the site, you agree to the updated terms.",
    termsLastUpdated: "Last updated",
    
    // About Section
    aboutTitle: "Flugart — Innovative Solutions for Drone Technologies",
    aboutText: "We are Flugart, a company specializing in manufacturing FPV drones of various sizes, creating custom batteries, producing fiber optic spools, and 3D printing drone parts. Our team ensures high quality and an individual approach to every order.",
    
    // Features Ticker
    feature1: "Components from trusted global brands",
    feature2: "More than 20,000 assemblies monthly",
    feature3: "Expert manufacturing experience",
    feature4: "Testing and verification of each product",
    feature5: "Own R&D department in Ukraine",
    feature6: "High-quality Ukrainian production",
    
    // Categories
    ourServices: "Our Services",
    view: "View",
    variousSizes: "various sizes",
    customOrder: "custom order",
    forDrones: "for drones",
    onDemand: "on demand",
    
    // Footer
    footerDescription: "Innovative technologies for FPV drones and premium quality components.",
    footerCatalog: "Catalog",
    footerInfo: "Information",
    footerContacts: "Contacts",
    footerAbout: "About us",
    footerAboutText: "Flugart is a Ukrainian company specializing in FPV drone manufacturing, batteries, fiber optic spools, and 3D printed components. Operating since 2022, we fulfill custom orders.",
    footerDelivery: "Delivery & Payment",
    footerWarranty: "Warranty",
    footerWarrantyTitle: "Warranty",
    footerWarrantyText: "6 months on all products of our own manufacture. Warranty does not cover mechanical damage and improper use.",
    footerContact: "Contact",
    footerRights: "© 2024 Flugart. All rights reserved.",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Use",
    footerBatteriesCustom: "Custom batteries",
    
    // About Page
    aboutPageTitle: "About Flugart",
    aboutPageSubtitle: "Innovative solutions for drone technologies",
    aboutMissionTitle: "Our Mission",
    aboutMissionText: "Flugart creates reliable and high-quality solutions for drone systems. We believe that Ukrainian technologies should be the best in the world, and we work on this every day.",
    aboutHistoryTitle: "Company History",
    aboutHistoryText: "Flugart was founded in 2022 in Ukraine. Since then, we have completed thousands of orders and built a reputation as a reliable partner for FPV pilots and organizations using drone technologies.",
    aboutServicesTitle: "What We Do",
    aboutService1: "Manufacturing FPV drones of various sizes (8\", 10\", 13\", 15\") TAIPAN and MAMBA series",
    aboutService2: "Custom battery assembly for individual customer needs",
    aboutService3: "Production of fiber optic spools for long-range systems",
    aboutService4: "3D printing of components and parts for drones",
    aboutTeamTitle: "Our Team",
    aboutTeamText: "The Flugart team consists of experienced engineers, designers, and FPV pilots who understand customer needs. Our own R&D department constantly works on product improvement.",
    aboutValuesTitle: "Our Values",
    aboutValue1: "Quality — we use only proven components from world brands",
    aboutValue2: "Individual approach — each order is fulfilled considering customer needs",
    aboutValue3: "Responsibility — we test every product before shipping",
    aboutLocationTitle: "Location",
    aboutLocationText: "We are based in Ukraine and deliver throughout the country.",
    
    // Delivery Page
    deliveryPageTitle: "Delivery & Payment",
    deliveryPageSubtitle: "Individual approach to each order",
    deliveryInfoTitle: "Delivery & Manufacturing Terms",
    deliveryInfoText: "Delivery and manufacturing times are calculated individually for each order. Delivery cost also depends on the specifics of the order.",
    deliveryGeographyTitle: "Delivery Geography",
    deliveryGeographyText: "We deliver throughout Ukraine. For orders from other countries, contact us to discuss terms.",
    paymentMethodsTitle: "Payment Methods",
    paymentCard: "Card Payment",
    paymentCardText: "Secure payment with Visa/Mastercard bank card.",
    paymentPrepayment: "Prepayment",
    paymentPrepaymentText: "Custom products may require partial or full prepayment. Terms are discussed individually.",
    deliveryQuestionsTitle: "Have Questions?",
    deliveryQuestionsText: "Contact us by phone to clarify delivery and payment details:",
    deliveryQuestionsTextEmail: "Contact us to clarify delivery and payment details:",
    
    // Warranty Page
    warrantyPageTitle: "Warranty",
    warrantyPageSubtitle: "Warranty service terms for Flugart products",
    warrantyPeriod: "6 months",
    warrantyPeriodText: "on all products of our own manufacture",
    warrantyTermsTitle: "General Terms",
    warrantyTerm1: "6 month warranty period from the date of product receipt",
    warrantyTerm2: "Warranty applies to Flugart's own manufactured products",
    warrantyTerm3: "Keep your purchase document for warranty claims",
    warrantyCoveredTitle: "What Warranty Covers",
    warrantyCovered1: "Manufacturing defects and material flaws",
    warrantyCovered2: "Electronic component failures with proper use",
    warrantyCovered3: "Battery issues (except natural wear)",
    warrantyCovered4: "Assembly and soldering defects",
    warrantyNotCoveredTitle: "What Warranty Does Not Cover",
    warrantyNotCovered1: "Mechanical damage from falls, impacts, crashes",
    warrantyNotCovered2: "Damage from improper use (overloading, incorrect charging)",
    warrantyNotCovered3: "Natural wear of components",
    warrantyNotCovered4: "Self-repair or product modification",
    warrantyClaimTitle: "How to Make a Warranty Claim",
    warrantyClaim1: "Contact us by phone or through the feedback form",
    warrantyClaim2: "Describe the problem and provide photo/video of the defect",
    warrantyClaim3: "After warranty case confirmation, send the product to our warehouse",
    warrantyClaim4: "We will repair or replace within 14 business days",
    warrantyContactTitle: "Warranty Contact",
    warrantyContactText: "For warranty claims, contact us:",
    warrantyContactTextEmail: "For warranty claims, email us:",
    
    // Search Results
    home: "Home",
    search: "Search",
    searchPlaceholder: "Search...",
    searchProductsPlaceholder: "Search products...",
    showAllResults: "Show all results",
    nothingFoundFor: "Nothing found for",
    searchResults: "Search results",
    allCategories: "All categories",
    categories: "Categories",
    foundProducts: "Found products",
    product: "product",
    products234: "products",
    products5plus: "products",
    nothingFound: "Nothing found",
    tryChangingSearch: "Try changing your search query or browse our categories",
    toHome: "Go to home",
    
    // Product Page
    inStock: "In stock",
    outOfStock: "Out of stock",
    pcs: "pcs",
    quantity: "Quantity",
    buyNow: "Buy now",
    addToCart: "Add to cart",
    addToFavorites: "Add to favorites",
    inFavorites: "In favorites",
    addedToFavorites: "Added to favorites",
    removedFromFavorites: "Removed from favorites",
    share: "Share",
    delivery: "Delivery",
    allUkraine: "All over Ukraine",
    warranty: "Warranty",
    months6: "6 months",
    returns: "Returns",
    days14: "14 days",
    specifications: "Specifications",
    features: "Features",
    addedToCart: "Added to cart",
    
    // Cart
    cart: "Cart",
    favorites: "Favorites",
    clear: "Clear",
    cartEmpty: "Cart is empty",
    favoritesEmpty: "Favorites is empty",
    addProductsToOrder: "Add products to place an order",
    addProductsToFavorites: "Add products to favorites",
    continueShopping: "Continue shopping",
    yourSavings: "Your savings",
    total: "Total",
    checkout: "Checkout",
    
    // Checkout
    orderCheckout: "Checkout",
    goBack: "Go back",
    contactInfo: "Contact information",
    firstName: "First name",
    lastName: "Last name",
    phone: "Phone",
    email: "Email",
    enterFirstName: "Enter first name",
    enterLastName: "Enter last name",
    enterPhone: "Enter phone number",
    deliveryMethod: "Delivery method",
    novaPoshta: "Nova Poshta",
    toWarehouse: "Delivery to warehouse",
    courier: "Courier",
    toAddress: "Delivery to address",
    city: "City",
    enterCity: "Enter city",
    warehouseNumber: "Warehouse number",
    deliveryAddress: "Delivery address",
    paymentMethod: "Payment method",
    cardPayment: "Card payment",
    cashOnDelivery: "Cash on delivery",
    payOnReceive: "Pay on receive",
    deliveryDiscussedPersonally: "Delivery method is discussed personally",
    paymentOnReceipt: "Payment on receipt",
    orderComment: "Order comment",
    additionalInfo: "Additional information about the order...",
    yourOrder: "Your order",
    discount: "Discount",
    deliveryCost: "According to carrier rates",
    confirmOrder: "Confirm order",
    agreeToTerms: "By clicking the button, you agree to the terms of the public offer",
    orderPlaced: "Order placed!",
    willContactYou: "We will contact you shortly",
    error: "Error",
    fillAllFields: "Please fill in all required fields",
    
    // Validation errors
    enterName: "Enter name",
    enterSurname: "Enter surname",
    enterPhoneNumber: "Enter phone number",
    enterEmail: "Enter email",
    invalidEmail: "Invalid email format",
    enterWarehouse: "Enter warehouse number",
    enterAddress: "Enter delivery address",
    
    // 404
    pageNotFound: "Page not found",
    returnToHome: "Return to home",
    
    // Category names
    "catFpvDrones": "FPV Drones",
    "catBatteries": "Batteries",
    "catFiberOptic": "Fiber Optic",
    "cat3dPrinting": "3D Printing",
    "accessories": "Accessories",
    
    // Popular products
    popularProducts: "Popular products",
    
    // Product names
    "product_fpv_5_freestyle": "FPV Drone 5\" Freestyle",
    "product_fpv_7_longrange": "FPV Drone 7\" Long Range",
    "product_fpv_3_cinewhoop": "FPV Drone 3\" Cinewhoop",
    "product_fpv_10_heavylift": "FPV Drone 10\" Heavy Lift",
    "product_battery_lipo_6s": "LiPo Battery 6S 1300mAh",
    "product_battery_lipo_4s": "LiPo Battery 4S 1500mAh",
    "product_battery_liion_21700": "Li-Ion Battery 21700 Assembly",
    "product_fiber_old_15km": "Fiber Optic Spool 15km",
    "product_fiber_old_20km": "Fiber Optic Spool 20km",
    "product_fiber_old_25km": "Fiber Optic Spool 25km",
    "product_3d_drone_case": "3D Printed Drone Case",
    "product_3d_camera_mount": "3D Printed Camera Mount",
    "product_3d_protection_frame": "3D Printed Protection Frame",
    "product_3d_antenna_holder": "3D Printed Antenna Holder",
    
    // Product page details
    "product1_title": "BTRY 6s2p Lishen (LR2170LA)",
    "product1_description": "High-quality BTRY 6s2p battery assembly based on Lishen LR2170LA cells. Ideal for medium and large FPV drones.",
    "product1_feature1": "High capacity for extended flight time",
    "product1_feature2": "Stable current output up to 90A",
    "product1_feature3": "Overcharge and overdischarge protection",
    "product1_feature4": "Heat-resistant case coating",
    "product1_feature5": "Quality spot welding",
    "product1_feature6": "6 months warranty",
    
    "product2_title": "Molicel INR21700-P42A",
    "product2_description": "Original high-drain Molicel INR21700-P42A cell. One of the best cells for FPV builds due to high current output and stability.",
    "product2_feature1": "Original Molicel cells",
    "product2_feature2": "High current output 45A",
    "product2_feature3": "Low internal resistance",
    "product2_feature4": "Stable operation at low temperatures",
    
    "product3_title": "BTRY Thermal Container with Heating",
    "product3_description": "Professional thermal container with built-in heating for storing and transporting Li-ion batteries in cold weather.",
    "product3_feature1": "Built-in heating system",
    "product3_feature2": "Camouflage coloring",
    "product3_feature3": "Impact-resistant case",
    "product3_feature4": "Hermetic closure",
    
    // Specification labels
    "spec_configuration": "Configuration",
    "spec_capacity": "Capacity",
    "spec_voltage": "Voltage",
    "spec_voltage_nominal": "22.2V (nominal)",
    "spec_voltage_nominal_36": "3.6V (nominal)",
    "spec_max_current": "Max current",
    "spec_weight": "Weight",
    "spec_dimensions": "Dimensions",
    "spec_cells": "Cells",
    "spec_bms": "BMS",
    "spec_bms_builtin": "Built-in protection board",
    "spec_form_factor": "Form factor",
    "spec_material": "Material",
    "spec_impact_resistant_plastic": "Impact-resistant plastic",
    "spec_insulation": "Insulation",
    "spec_thermal_insulation": "Thermal insulation 20mm",
    "spec_heating": "Heating",
    "spec_up_to_12_batteries": "Up to 12 batteries",
    
    // Fiber optic
    "fiber_15km_description": "15 km fiber optic spool for FPV drones. Provides stable communication over long distances with minimal signal loss.",
    "fiber_20km_description": "20 km fiber optic spool for FPV drones. Ideal choice for medium-range flights with high-quality data transmission.",
    "fiber_25km_description": "25 km fiber optic spool for FPV drones. Maximum range for professional operations with uninterrupted communication.",
    "spec_length": "Length",
    "spec_fiber_type": "Fiber type",
    "spec_single_mode": "Single-mode",
    "spec_core_diameter": "Core diameter",
    "spec_attenuation": "Attenuation",
    "fiber_feature1": "Stable communication over long distances",
    "fiber_feature2": "Minimal signal loss",
    "fiber_feature3": "High-quality fiber",
    "fiber_feature4": "Resistance to electromagnetic interference",
    
    // Drone specs translations
    "spec_flight_stack": "Flight Stack",
    "spec_motors": "Motors",
    "spec_frame": "Frame",
    "spec_video_tx": "Video Transmitter",
    "spec_camera": "Camera",
    "spec_receiver": "Receiver",
    "spec_propellers": "Propellers",
    "spec_battery": "Battery",
    "spec_antenna": "Antenna",
    "spec_fiber_optic": "Fiber Optic",
    
    // Drone features translations
    "feature_carbon_frame": "Carbon frame",
    "feature_day_camera": "Day camera",
    "feature_thermal_camera": "Thermal camera",
    "feature_lowlight_camera": "Low-light camera",
    "feature_diversity_camera": "Diversity camera",
    "feature_powerful_vtx": "Powerful video transmitter",
    "feature_fiber_optic": "Fiber optic",
    "feature_rotary_mount": "Rotary camera mount",
    "feature_3d_printed_case": "3D printed case",
    "feature_quick_mount": "Quick mount",
    "feature_stable_connection": "Stable interference-free connection",
    
    // Additional UI
    linkCopied: "Link copied",
    menu: "Menu",
    language: "Language",
    callUs: "Call us",
    sortBy: "Sort by",
    priceAsc: "Price: low to high",
    priceDesc: "Price: high to low",
    nameAz: "Name: A-Z",
    nameZa: "Name: Z-A",
    product_fiber_10km: "Fiber Optic Spool 10km",
    product_fiber_15km: "Fiber Optic Spool 15km",
    product_fiber_20km: "Fiber Optic Spool 20km",
    location: "Ukraine, Kyiv",
    defaultSort: "Default",
    configurator: "Configurator",
    
    // Footer
    footerInstruction: "Instructions",
    
    // Instructions page
    instructionTitle: "UAV Operating Instructions",
    instructionIntro: "Detailed instructions for preparation and operation of unmanned aerial vehicles with fiber optic connection.",
    checkUavCompleteness: "Check UAV Completeness",
    uavItem1: "Battery",
    uavItem2: "Fiber optic cable spool, spool holder",
    uavItem3: "Initiation board",
    uavItem4: "Velcro straps or plastic cable ties",
    checkStationCompleteness: "Check Ground Station Completeness",
    stationItem1: "Signal converter",
    stationItem2: "Battery",
    stationItem3: "Video cable",
    prepareForOperation: "Preparation for Operation",
    prepareStep1: "Install the spool on the appropriate mount under the UAV in the direction from the camera back to the stop, insert the spool lock into the corresponding hole on the mount",
    prepareStep2: "Carefully connect the cable from the UAV to the spool",
    prepareStep3: "Install the warhead",
    prepareStep4: "Install the initiation board directly on the warhead or in the appropriate mounting location on the UAV frame side, secure with ties, connect the warhead detonator to the initiation board, if necessary connect the initiation board to the UAV (green connector)",
    prepareStep5: "Install the battery in the appropriate place, rear part of the UAV between the frame and the spool, secure with straps or ties",
    controllerSettings: "Controller Settings",
    controllerSettingsIntro: "In the controller settings, enable the external module (External) in PPM mode. The following channels are used to control the UAV:",
    channelAETR: "standard AETR sequence",
    channelARM: "motor start (ARM): STOP ~1000, START ~2000",
    channelModes: "flight modes: ACRO ~1000, ANGLE ~1500, HORIZON ~2000",
    channelActivation: "warhead activation ~2000",
    preFlightPrep: "Pre-Flight Preparation",
    preFlightIntro: "Check the balance of the assembled UAV, the center of gravity should be in the middle or with a slight forward deviation. Proper balancing will allow more efficient use of battery energy in flight.",
    preFlightPlace: "Place the UAV on a special stand or use improvised means.",
    spoolPrep: "Spool Preparation:",
    spoolStep1: "Cut the tie and remove the fiber optic cable exit guards",
    spoolStep2: "Remove the protective red tape and protective cap",
    spoolStep3: "CAREFULLY remove the protective cap on the connector",
    spoolStep4: "CAREFULLY pull out enough cable and connect to the ground station",
    spoolStep5: "DO NOT bend the fiber optic cable",
    connectionStep1: "Connect the ground station battery to the signal converter, connect the video cable with the appropriate end to the signal converter, the other to goggles or monitor, connect the cable to the controller",
    connectionStep2: "Turn on the ground station, goggles or monitor, controller",
    connectionStep3: "Connect the UAV power cable, check the light indication on the spool and ground station, check the video in goggles or on the monitor",
    connectionStep4: "Turn on the motors with the appropriate switch on the controller, all propellers should rotate, rotation direction \"towards the camera\"",
    takeoffTitle: "Takeoff",
    takeoffText: "Take off up and forward. At the moment of takeoff, hold the fiber optic cable, wait until it lies on the ground, bushes, trees, etc., after which the cable can no longer be held.",
    flightControlTitle: "Flight Control",
    flightControlWarning: "Avoid sharp maneuvering, stopping and ESPECIALLY flying backwards, this can lead to fiber optic cable breakage.",
    happyFlight: "We wish you a pleasant flight and successful completion!",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "uk";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
